In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (4.24.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.2)
Requirement already satisfied: trio~=0.17 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.26.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (24.2.0)
Requirement already satisfied: sortedcontainers in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (3.8)
Requirement already satisfied: outcome in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from trio~=0.17->selenium) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.22)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome()

driver.get("https://www.redbus.in/online-booking/apsrtc/?utm_source=rtchometile")

driver.maximize_window()

time.sleep(5)

old_price_source=driver.page_source

route_Andhra=driver.find_elements(By.CSS_SELECTOR,"a[<a href='/bus-tickets/hyderabad-to-vijayawada']")

InvalidSelectorException: Message: invalid selector
from javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=128.0.6613.119); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7538F9412+29090]
	(No symbol) [0x00007FF75386E239]
	(No symbol) [0x00007FF75372B1DA]
	(No symbol) [0x00007FF753731CE3]
	(No symbol) [0x00007FF753734081]
	(No symbol) [0x00007FF753734120]
	(No symbol) [0x00007FF75377EB5C]
	(No symbol) [0x00007FF75377F23C]
	(No symbol) [0x00007FF7537C97F7]
	(No symbol) [0x00007FF7537A672F]
	(No symbol) [0x00007FF7537C65A2]
	(No symbol) [0x00007FF7537A6493]
	(No symbol) [0x00007FF7537709D1]
	(No symbol) [0x00007FF753771B31]
	GetHandleVerifier [0x00007FF753C1871D+3302573]
	GetHandleVerifier [0x00007FF753C64243+3612627]
	GetHandleVerifier [0x00007FF753C5A417+3572135]
	GetHandleVerifier [0x00007FF7539B5EB6+801862]
	(No symbol) [0x00007FF75387945F]
	(No symbol) [0x00007FF753874FB4]
	(No symbol) [0x00007FF753875140]
	(No symbol) [0x00007FF75386461F]
	BaseThreadInitThunk [0x00007FFB1B62244D+29]
	RtlUserThreadStart [0x00007FFB1C76DF78+40]

In [12]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

#implicit wait
wait = WebDriverWait(driver, 20)

def Kerala_link_route(path):   
    LINKS_KERALA = []
    ROUTE_KERALA = []

    # Retrieve the route links and route names
    for i in range(1, 4):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_KERALA.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_KERALA.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_KERALA, ROUTE_KERALA

# Calling the function to get links and routes
LINKS_KERALA, ROUTE_KERALA = Kerala_link_route("//a[@class='route']")

No more pages to paginate at step 2

In [20]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [21]:
driver=webdriver.Chrome()

#load the webpage

driver.get("https://www.redbus.in/online-booking/tsrtc/?utm_source=rtchometile")

time.sleep(3)

driver.maximize_window()

In [22]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

#implicit wait
wait = WebDriverWait(driver, 20)

def Telugana_link_route(path):   
    LINKS_TELUGANA = []
    ROUTE_TELUGANA = []

    # Retrieve the route links and route names
    for i in range(1, 4):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_TELUGANA.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_TELUGANA.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_TELUGANA, ROUTE_TELUGANA

# Calling the function to get links and routes
LINKS_TELUGANA, ROUTE_TELUGAN = Telugana_link_route("//a[@class='route']")

No more pages to paginate at step 3

In [24]:
df_k=pd.DataFrame({"Route_name":ROUTE_TELUGANA,"Route_link":LINKS_TELUGANA})
df_k

,Route_name,Route_link
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...
1,Khammam to Hyderabad,https://www.redbus.in/bus-tickets/khammam-to-h...
2,Hyderabad to Khammam,https://www.redbus.in/bus-tickets/hyderabad-to...
3,Hyderabad to Srisailam,https://www.redbus.in/bus-tickets/hyderabad-to...
4,Karimnagar to Hyderabad,https://www.redbus.in/bus-tickets/karimnagar-t...
5,Hyderabad to Karimnagar,https://www.redbus.in/bus-tickets/hyderabad-to...
6,Hyderabad to Mancherial,https://www.redbus.in/bus-tickets/hyderabad-to...
7,Hyderabad to Nirmal,https://www.redbus.in/bus-tickets/hyderabad-to...
8,Hyderabad to Adilabad,https://www.redbus.in/bus-tickets/hyderabad-to...
9,Hyderabad to Ongole,https://www.redbus.in/bus-tickets/hyderabad-to...
10,Kothagudem to Hyderabad,https://www.redbus.in/bus-tickets/kothagudem-t...
11,Guntur (Andhra Pradesh) to Hyderabad,https://www.redbus.in/bus-tickets/guntur-to-hy...
12,Hyderabad to Guntur (Andhra Pradesh),https://www.redbus.in/bus-tickets/hyderabad-to...
13,Godavarikhani to Hyderabad,https://www.redbus.in/bus-tickets/godavarikhan...
14,Hyderabad to Kothagudem,https://www.redbus.in/bus-tickets/hyderabad-to...
15,Hyderabad to Sathupally,https://www.redbus.in/bus-tickets/hyderabad-to...
16,Hyderabad to Warangal,https://www.redbus.in/bus-tickets/hyderabad-to...
17,Kodad to Hyderabad,https://www.redbus.in/bus-tickets/kodad-to-hyd...
18,Jagityal to Hyderabad,https://www.redbus.in/bus-tickets/jagityal-to-...
19,Hyderabad to Bhadrachalam,https://www.redbus.in/bus-tickets/hyderabad-to...
20,Hyderabad to Tirupati,https://www.redbus.in/bus-tickets/hyderabad-to...
21,Hyderabad to Godavarikhani,https://www.redbus.in/bus-tickets/hyderabad-to...
22,Hyderabad to Armoor,https://www.redbus.in/bus-tickets/hyderabad-to...
23,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...
24,Hyderabad to Kodad,https://www.redbus.in/bus-tickets/hyderabad-to...
25,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...

In [25]:
df = df_k

In [26]:
#retrive the bus details
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names = []
Route_links = []

for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(2)  

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    scrolling = True
    while scrolling:
        old_page_source = driver_k.page_source
        
        # Use ActionChains to perform a PAGE_DOWN
        ActionChains(driver_k).send_keys(Keys.PAGE_DOWN).perform()
        
        time.sleep(5)  
        
        new_page_source = driver_k.page_source
        
        if new_page_source == old_page_source:
            scrolling = False

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links.append(link)
        Route_names.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [27]:
data = {
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'End_time': End_Time_k,
    'Total_duration': Total_Duration_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k,
    "Ratings":Ratings_k,
    'Route_link': Route_links,
    'Route_name': Route_names
}

df1 = pd.DataFrame(data)

In [187]:
df1.to_csv("C:/Users/USER/Downloads/TELUGANA_redbus.csv")

In [168]:
driver=webdriver.Chrome()

#load the webpage

driver.get("https://www.redbus.in/online-booking/ktcl/?utm_source=rtchometile")

time.sleep(3)

driver.maximize_window()

In [169]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

#implicit wait
wait = WebDriverWait(driver, 20)

def Kadamba_link_route(path):   
    LINKS_KADAMBA = []
    ROUTE_KADAMBA = []

    # Retrieve the route links and route names
    for i in range(1, 4):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_KADAMBA.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_KADAMBA.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_KADAMBA, ROUTE_KADAMBA

# Calling the function to get links and routes
LINKS_KADAMBA, ROUTE_KADAMBA = Kadamba_link_route("//a[@class='route']")

In [170]:
df_k=pd.DataFrame({"Route_name":ROUTE_KADAMBA,"Route_link":LINKS_KADAMBA})
df_k

,Route_name,Route_link
0,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa
1,Goa to Pune,https://www.redbus.in/bus-tickets/goa-to-pune
2,Mumbai to Goa,https://www.redbus.in/bus-tickets/mumbai-to-goa
3,Bangalore to Goa,https://www.redbus.in/bus-tickets/bangalore-to...
4,Goa to Bangalore,https://www.redbus.in/bus-tickets/goa-to-banga...
5,Goa to Mumbai,https://www.redbus.in/bus-tickets/goa-to-mumbai
6,Pandharpur to Goa,https://www.redbus.in/bus-tickets/pandharpur-t...
7,Goa to Pandharpur,https://www.redbus.in/bus-tickets/goa-to-pandh...
8,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa
9,Calangute (goa) to Goa Airport,https://www.redbus.in/bus-tickets/calangute-go...
10,Goa to Kolhapur(Maharashtra),https://www.redbus.in/bus-tickets/goa-to-kolha...
11,Goa to Solapur,https://www.redbus.in/bus-tickets/goa-to-solapur
12,Goa to Sangli,https://www.redbus.in/bus-tickets/goa-to-sangli
13,Goa Airport to Calangute (goa),https://www.redbus.in/bus-tickets/goa-airport-...
14,Goa to Sangola (Solapur),https://www.redbus.in/bus-tickets/goa-to-sangola
15,Sangola (Solapur) to Goa,https://www.redbus.in/bus-tickets/sangola-to-goa
16,Mopa Airport to Calangute (goa),https://www.redbus.in/bus-tickets/mopa-airport...
17,Calangute (goa) to Mopa Airport,https://www.redbus.in/bus-tickets/calangute-go...
18,Goa to Mopa Airport,https://www.redbus.in/bus-tickets/goa-to-mopa-...
19,Goa to Miraj,https://www.redbus.in/bus-tickets/goa-to-miraj
20,Panaji to Goa Airport,https://www.redbus.in/bus-tickets/panaji-to-go...
21,Mopa Airport to Goa,https://www.redbus.in/bus-tickets/mopa-airport...
22,Shivamogga to Goa,https://www.redbus.in/bus-tickets/shimoga-to-goa
23,Margao to Mopa Airport,https://www.redbus.in/bus-tickets/margoa-to-mo...
24,Goa Airport to Goa,https://www.redbus.in/bus-tickets/goa-airport-...
25,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara
26,Goa to Goa Airport,https://www.redbus.in/bus-tickets/goa-to-goa-a...
27,Goa Airport to Panaji,https://www.redbus.in/bus-tickets/goa-airport-...
28,Goa to Shirdi,https://www.redbus.in/bus-tickets/goa-to-shirdi
29,Calangute (goa) to Panaji,https://www.redbus.in/bus-tickets/calangute-go...

In [171]:
df = df_k

In [172]:
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names = []
Route_links = []

for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(2)  

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    scrolling = True
    while scrolling:
        old_page_source = driver_k.page_source
        
        # Use ActionChains to perform a PAGE_DOWN
        ActionChains(driver_k).send_keys(Keys.PAGE_DOWN).perform()
        
        time.sleep(5)  
        
        new_page_source = driver_k.page_source
        
        if new_page_source == old_page_source:
            scrolling = False

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links.append(link)
        Route_names.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [173]:
data = {
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'End_time': End_Time_k,
    'Total_duration': Total_Duration_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k,
    "Ratings":Ratings_k,
    'Route_link': Route_links,
    'Route_name': Route_names
}

df2 = pd.DataFrame(data)

In [174]:
df2.to_csv("C:/Users/USER/Downloads/red_bus_data3.csv")

In [78]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [79]:
driver=webdriver.Chrome()

#load the webpage

driver.get("https://www.redbus.in/online-booking/rsrtc/?utm_source=rtchometile")

time.sleep(3)

driver.maximize_window()

In [80]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

#implicit wait
wait = WebDriverWait(driver, 20)

def Rajastan_link_route(path):   
    LINKS_RAJASTAN = []
    ROUTE_RAJASTAN = []

    # Retrieve the route links and route names
    for i in range(1, 4):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_RAJASTAN.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_RAJASTAN.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_RAJASTAN, ROUTE_RAJASTAN

# Calling the function to get links and routes
LINKS_RAJASTAN, ROUTE_RAJASTAN = Rajastan_link_route("//a[@class='route']")

No more pages to paginate at step 2

In [81]:
df_R=pd.DataFrame({"Route_name":ROUTE_RAJASTAN,"Route_link":LINKS_RAJASTAN})
df_R

,Route_name,Route_link
0,Udaipur to Jodhpur,https://www.redbus.in/bus-tickets/udaipur-to-j...
1,Jodhpur to Ajmer,https://www.redbus.in/bus-tickets/jodhpur-to-a...
2,Beawar (Rajasthan) to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/beawer-to-ja...
3,Sikar to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/sikar-to-jaipur
4,Jaipur (Rajasthan) to Jodhpur,https://www.redbus.in/bus-tickets/jaipur-to-jo...
5,Aligarh (uttar pradesh) to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/aligarh-utta...
6,Jaipur (Rajasthan) to Aligarh (uttar pradesh),https://www.redbus.in/bus-tickets/jaipur-to-al...
7,Jodhpur to Beawar (Rajasthan),https://www.redbus.in/bus-tickets/jodhpur-to-b...
8,Jaipur (Rajasthan) to Pilani,https://www.redbus.in/bus-tickets/jaipur-to-pi...
9,Kishangarh to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/kishangarh-t...
10,Pali (Rajasthan) to Udaipur,https://www.redbus.in/bus-tickets/pali-to-udaipur
11,Udaipur to Pali (Rajasthan),https://www.redbus.in/bus-tickets/udaipur-to-p...
12,Kota(Rajasthan) to Udaipur,https://www.redbus.in/bus-tickets/kota-rajasth...
13,Jaipur (Rajasthan) to Bhilwara,https://www.redbus.in/bus-tickets/jaipur-to-bh...
14,Sikar to Bikaner,https://www.redbus.in/bus-tickets/sikar-to-bik...
15,Jaipur (Rajasthan) to Bharatpur,https://www.redbus.in/bus-tickets/jaipur-to-bh...
16,Jaipur (Rajasthan) to Mathura,https://www.redbus.in/bus-tickets/jaipur-to-ma...
17,Jaipur (Rajasthan) to Kota(Rajasthan),https://www.redbus.in/bus-tickets/jaipur-to-ko...

In [83]:
df = df_R

In [84]:
#retrive the bus details
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names = []
Route_links = []

for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(2)  

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    scrolling = True
    while scrolling:
        old_page_source = driver_k.page_source
        
        # Use ActionChains to perform a PAGE_DOWN
        ActionChains(driver_k).send_keys(Keys.PAGE_DOWN).perform()
        
        time.sleep(5)  
        
        new_page_source = driver_k.page_source
        
        if new_page_source == old_page_source:
            scrolling = False

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links.append(link)
        Route_names.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [85]:
data = {
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'End_time': End_Time_k,
    'Total_duration': Total_Duration_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k,
    "Ratings":Ratings_k,
    'Route_link': Route_links,
    'Route_name': Route_names
}

df3 = pd.DataFrame(data)

In [86]:
df3.to_csv("C:/Users/USER/Downloads/red_bus_data4.csv")

In [103]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

In [104]:
driver=webdriver.Chrome()

#load the webpage

driver.get("https://www.redbus.in/online-booking/south-bengal-state-transport-corporation-sbstc/?utm_source=rtchometile")

time.sleep(3)

driver.maximize_window()

In [107]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

#implicit wait
wait = WebDriverWait(driver, 20)

def Southbengal_link_route(path):   
    LINKS_SOUTHBENGAL = []
    ROUTE_SOUTHBENGAL = []

    # Retrieve the route links and route names
    for i in range(1, 6):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_SOUTHBENGAL.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_SOUTHBENGAL.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_SOUTHBENGAL, ROUTE_SOUTHBENGAL

# Calling the function to get links and routes
LINKS_SOUTHBENGAL, ROUTE_SOUTHBENGAL = Southbengal_link_route("//a[@class='route']")

No more pages to paginate at step 5

In [109]:
df_SB=pd.DataFrame({"Route_name":ROUTE_SOUTHBENGAL,"Route_link":LINKS_SOUTHBENGAL})
df_SB

,Route_name,Route_link
0,Berhampore (West Bengal) to Durgapur (West Ben...,https://www.redbus.in/bus-tickets/berhampore-t...
1,Purulia to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/purulia-to-d...
2,Durgapur (West Bengal) to Berhampore (West Ben...,https://www.redbus.in/bus-tickets/durgapur-to-...
3,Kolkata to Futishanko,https://www.redbus.in/bus-tickets/kolkata-to-f...
4,Kolkata to Kirnahar (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-k...
5,Durgapur (West Bengal) to Barasat (West Bengal),https://www.redbus.in/bus-tickets/durgapur-to-...
6,Kolkata to Ramnagar (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-r...
7,Durgapur (West Bengal) to Purulia,https://www.redbus.in/bus-tickets/durgapur-to-...
8,Durgapur (West Bengal) to Bankura,https://www.redbus.in/bus-tickets/durgapur-to-...
9,Kolkata to Ashari,https://www.redbus.in/bus-tickets/kolkata-to-a...
10,Kolkata to Midnapore,https://www.redbus.in/bus-tickets/kolkata-to-m...
11,Kolkata to Asansol (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-a...
12,Kolkata to Nimtouri,https://www.redbus.in/bus-tickets/kolkata-to-n...
13,Jhargram to Kolkata,https://www.redbus.in/bus-tickets/jhargram-to-...
14,Kolkata to Contai (Kanthi),https://www.redbus.in/bus-tickets/kolkata-to-c...
15,Kolkata to Kolaghat,https://www.redbus.in/bus-tickets/kolkata-to-k...
16,Kolkata to Nandakumar (west bengal),https://www.redbus.in/bus-tickets/kolkata-to-n...
17,Kolkata to Mecheda (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-m...
18,Digha to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/digha-to-dur...
19,Midnapore to Barasat (West Bengal),https://www.redbus.in/bus-tickets/midnapore-to...
20,Durgapur (West Bengal) to Digha,https://www.redbus.in/bus-tickets/durgapur-to-...
21,Kolkata to Chandipur (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-c...
22,Barasat (West Bengal) to Midnapore,https://www.redbus.in/bus-tickets/barasat-west...
23,Kolkata to Debra,https://www.redbus.in/bus-tickets/kolkata-to-d...
24,Kirnahar (West Bengal) to Kolkata,https://www.redbus.in/bus-tickets/kirnahar-wes...
25,Kolkata to Panskura,https://www.redbus.in/bus-tickets/kolkata-to-p...
26,Kolkata to Heria,https://www.redbus.in/bus-tickets/kolkata-to-h...
27,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...
28,Illambazar to Kolkata,https://www.redbus.in/bus-tickets/illambazar-t...
29,Kolkata to Suri,https://www.redbus.in/bus-tickets/kolkata-to-suri
30,Berhampore (West Bengal) to Durgapur (West Ben...,https://www.redbus.in/bus-tickets/berhampore-t...
31,Purulia to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/purulia-to-d...
32,Durgapur (West Bengal) to Berhampore (West Ben...,https://www.redbus.in/bus-tickets/durgapur-to-...
33,Kolkata to Futishanko,https://www.redbus.in/bus-tickets/kolkata-to-f...
34,Kolkata to Kirnahar (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-k...
35,Durgapur (West Bengal) to Barasat (West Bengal),https://www.redbus.in/bus-tickets/durgapur-to-...
36,Kolkata to Ramnagar (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-r...
37,Durgapur (West Bengal) to Purulia,https://www.redbus.in/bus-tickets/durgapur-to-...
38,Durgapur (West Bengal) to Bankura,https://www.redbus.in/bus-tickets/durgapur-to-...
39,Kolkata to Ashari,https://www.redbus.in/bus-tickets/kolkata-to-a...
40,Barasat (West Bengal) to Digha,https://www.redbus.in/bus-tickets/barasat-west...

In [110]:
df = df_SB

In [111]:
#retrive the bus details
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names = []
Route_links = []

for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(2)  

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    scrolling = True
    while scrolling:
        old_page_source = driver_k.page_source
        
        # Use ActionChains to perform a PAGE_DOWN
        ActionChains(driver_k).send_keys(Keys.PAGE_DOWN).perform()
        
        time.sleep(5)  
        
        new_page_source = driver_k.page_source
        
        if new_page_source == old_page_source:
            scrolling = False

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links.append(link)
        Route_names.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [112]:
data = {
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'End_time': End_Time_k,
    'Total_duration': Total_Duration_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k,
    "Ratings":Ratings_k,
    'Route_link': Route_links,
    'Route_name': Route_names
}

df4 = pd.DataFrame(data)

In [113]:
df4.to_csv("C:/Users/USER/Downloads/red_bus_data6.csv")

In [114]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

In [115]:
driver=webdriver.Chrome()

#load the webpage

driver.get("https://www.redbus.in/online-booking/hrtc/?utm_source=rtchometile")

time.sleep(3)

driver.maximize_window()

In [116]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

#implicit wait
wait = WebDriverWait(driver, 20)

def Haryana_link_route(path):   
    LINKS_HARYANA = []
    ROUTE_HARYANA = []

    # Retrieve the route links and route names
    for i in range(1, 6):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_HARYANA.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_HARYANA.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_HARYANA, ROUTE_HARYANA

# Calling the function to get links and routes
LINKS_HARYANA, ROUTE_HARYANA = Haryana_link_route("//a[@class='route']")

No more pages to paginate at step 4

In [117]:
df_H=pd.DataFrame({"Route_name":ROUTE_HARYANA,"Route_link":LINKS_HARYANA})
df_H

,Route_name,Route_link
0,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla
1,Chandigarh to Hamirpur (Himachal Pradesh),https://www.redbus.in/bus-tickets/chandigarh-t...
2,Hamirpur (Himachal Pradesh) to Chandigarh,https://www.redbus.in/bus-tickets/hamirpur-him...
3,Shimla to Delhi,https://www.redbus.in/bus-tickets/shimla-to-delhi
4,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...
5,Hamirpur (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/hamirpur-him...
6,Chamba (Himachal Pradesh) to Chandigarh,https://www.redbus.in/bus-tickets/chamba-himac...
7,Delhi to Hamirpur (Himachal Pradesh),https://www.redbus.in/bus-tickets/delhi-to-ham...
8,Chandigarh to Dharamshala (Himachal Pradesh),https://www.redbus.in/bus-tickets/chandigarh-t...
9,Delhi to Chamba (Himachal Pradesh),https://www.redbus.in/bus-tickets/delhi-to-cha...
10,Chamba (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/chamba-himac...
11,Kangra to Chandigarh,https://www.redbus.in/bus-tickets/kangra-to-ch...
12,Shimla to Chandigarh,https://www.redbus.in/bus-tickets/shimla-to-ch...
13,Delhi to Baddi (Himachal Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bad...
14,Delhi to Solan,https://www.redbus.in/bus-tickets/delhi-to-solan
15,Delhi to Nalagarh,https://www.redbus.in/bus-tickets/delhi-to-nal...
16,Dharamshala (Himachal Pradesh) to Chandigarh,https://www.redbus.in/bus-tickets/dharamshala-...
17,Palampur to Chandigarh,https://www.redbus.in/bus-tickets/palampur-to-...
18,Ghumarwin to Delhi,https://www.redbus.in/bus-tickets/ghumarwin-to...
19,Chandigarh to Kangra,https://www.redbus.in/bus-tickets/chandigarh-t...
20,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...
21,Manali to Chandigarh,https://www.redbus.in/bus-tickets/manali-to-ch...
22,Solan to Delhi,https://www.redbus.in/bus-tickets/solan-to-delhi
23,Chandigarh to Manali,https://www.redbus.in/bus-tickets/chandigarh-t...
24,Delhi to Sarkaghat,https://www.redbus.in/bus-tickets/delhi-to-sar...
25,Ghumarwin to Chandigarh,https://www.redbus.in/bus-tickets/ghumarwin-to...
26,Chandigarh to Kullu,https://www.redbus.in/bus-tickets/chandigarh-t...
27,Delhi to Bilaspur (Himachal Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bil...
28,Delhi to Ghumarwin,https://www.redbus.in/bus-tickets/delhi-to-ghu...
29,Chamba (Himachal Pradesh) to Shimla,https://www.redbus.in/bus-tickets/chamba-himac...
30,Delhi to Palampur,https://www.redbus.in/bus-tickets/delhi-to-pal...
31,Chandigarh to Reckong Peo (Himachal Pradesh),https://www.redbus.in/bus-tickets/chandigarh-t...
32,Bilaspur (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/bilaspur-him...
33,Sarkaghat to Delhi,https://www.redbus.in/bus-tickets/sarkaghat-to...
34,Manali to Delhi,https://www.redbus.in/bus-tickets/manali-to-delhi

In [118]:
df = df_H

In [119]:
#retrive the bus details
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names = []
Route_links = []

for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(2)  

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    scrolling = True
    while scrolling:
        old_page_source = driver_k.page_source
        
        # Use ActionChains to perform a PAGE_DOWN
        ActionChains(driver_k).send_keys(Keys.PAGE_DOWN).perform()
        
        time.sleep(5)  
        
        new_page_source = driver_k.page_source
        
        if new_page_source == old_page_source:
            scrolling = False

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links.append(link)
        Route_names.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [120]:
data = {
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'End_time': End_Time_k,
    'Total_duration': Total_Duration_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k,
    "Ratings":Ratings_k,
    'Route_link': Route_links,
    'Route_name': Route_names
}

df5 = pd.DataFrame(data)

In [183]:
df5.to_csv("C:/Users/USER/Downloads/HARYANA_redbus.csv")

In [122]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

In [188]:
driver=webdriver.Chrome()

#load the webpage

driver.get("https://www.redbus.in/online-booking/pepsu/?utm_source=rtchometile")

time.sleep(3)

driver.maximize_window()

In [189]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

#implicit wait
wait = WebDriverWait(driver, 20)

def Punjab_link_route(path):   
    LINKS_PUNJAB = []
    ROUTE_PUNJAB = []

    # Retrieve the route links and route names
    for i in range(1, 5):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_PUNJAB.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_PUNJAB.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_PUNJAB, ROUTE_PUNJAB

# Calling the function to get links and routes
LINKS_PUNJAB, ROUTE_PUNJAB = Punjab_link_route("//a[@class='route']")

No more pages to paginate at step 2

In [190]:
df_PJ=pd.DataFrame({"Route_name":ROUTE_PUNJAB,"Route_link":LINKS_PUNJAB})
df_PJ

,Route_name,Route_link
0,Delhi to Patiala,https://www.redbus.in/bus-tickets/delhi-to-pat...
1,Patiala to Delhi,https://www.redbus.in/bus-tickets/patiala-to-d...
2,Delhi to Ludhiana,https://www.redbus.in/bus-tickets/delhi-to-lud...
3,Ludhiana to Delhi,https://www.redbus.in/bus-tickets/ludhiana-to-...
4,Jalandhar to Delhi,https://www.redbus.in/bus-tickets/jalandhar-to...
5,Delhi to Jalandhar,https://www.redbus.in/bus-tickets/delhi-to-jal...
6,Delhi Airport to Patiala,https://www.redbus.in/bus-tickets/delhi-airpor...
7,Ludhiana to Delhi Airport,https://www.redbus.in/bus-tickets/ludhiana-to-...
8,Delhi Airport to Ludhiana,https://www.redbus.in/bus-tickets/delhi-airpor...
9,Jalandhar to Delhi Airport,https://www.redbus.in/bus-tickets/jalandhar-to...
10,Phagwara to Delhi Airport,https://www.redbus.in/bus-tickets/phagwara-to-...
11,Delhi to Phagwara,https://www.redbus.in/bus-tickets/delhi-to-pha...
12,Delhi Airport to Jalandhar,https://www.redbus.in/bus-tickets/delhi-airpor...
13,Phagwara to Delhi,https://www.redbus.in/bus-tickets/phagwara-to-...
14,Delhi to Amritsar,https://www.redbus.in/bus-tickets/delhi-to-amr...
15,Amritsar to Delhi,https://www.redbus.in/bus-tickets/amritsar-to-...
16,Amritsar to Delhi Airport,https://www.redbus.in/bus-tickets/amritsar-to-...
17,Delhi Airport to Phagwara,https://www.redbus.in/bus-tickets/delhi-airpor...

In [191]:
df = df_PJ

In [192]:
#retrive the bus details
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names = []
Route_links = []

for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(2)  

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    scrolling = True
    while scrolling:
        old_page_source = driver_k.page_source
        
        # Use ActionChains to perform a PAGE_DOWN
        ActionChains(driver_k).send_keys(Keys.PAGE_DOWN).perform()
        
        time.sleep(5)  
        
        new_page_source = driver_k.page_source
        
        if new_page_source == old_page_source:
            scrolling = False

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links.append(link)
        Route_names.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [193]:
data = {
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'End_time': End_Time_k,
    'Total_duration': Total_Duration_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k,
    "Ratings":Ratings_k,
    'Route_link': Route_links,
    'Route_name': Route_names
}

df6 = pd.DataFrame(data)

In [194]:
df6.to_csv("C:/Users/USER/Downloads/red_bus_data8.csv")

In [134]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

In [135]:
driver=webdriver.Chrome()

#load the webpage

driver.get("https://www.redbus.in/online-booking/uttar-pradesh-state-road-transport-corporation-upsrtc/?utm_source=rtchometile")

time.sleep(3)

driver.maximize_window()

In [136]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

#implicit wait
wait = WebDriverWait(driver, 20)

def UP_link_route(path):   
    LINKS_UTTRAPRADESH = []
    ROUTE_UTTRAPRADESH = []

    # Retrieve the route links and route names
    for i in range(1, 6):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_UTTRAPRADESH.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_UTTRAPRADESH.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_UTTRAPRADESH, ROUTE_UTTRAPRADESH

# Calling the function to get links and routes
LINKS_UTTRAPRADESH, ROUTE_UTTRAPRADESH = UP_link_route("//a[@class='route']")

No more pages to paginate at step 5

In [137]:
df_UP=pd.DataFrame({"Route_name":ROUTE_UTTRAPRADESH,"Route_link":LINKS_UTTRAPRADESH})
df_UP

,Route_name,Route_link
0,Delhi to Bareilly,https://www.redbus.in/bus-tickets/delhi-to-bar...
1,Bareilly to Delhi,https://www.redbus.in/bus-tickets/bareilly-to-...
2,Aligarh (uttar pradesh) to Delhi,https://www.redbus.in/bus-tickets/aligarh-utta...
3,Delhi to Aligarh (uttar pradesh),https://www.redbus.in/bus-tickets/delhi-to-ali...
4,Lucknow to Allahabad,https://www.redbus.in/bus-tickets/lucknow-to-a...
5,Lucknow to Delhi,https://www.redbus.in/bus-tickets/lucknow-to-d...
6,Delhi to Farrukhabad (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-far...
7,Farrukhabad (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/farrukhabad-...
8,Badaun to Delhi,https://www.redbus.in/bus-tickets/badaun-to-delhi
9,Allahabad to Lucknow,https://www.redbus.in/bus-tickets/allahabad-to...
10,Lucknow to Agra,https://www.redbus.in/bus-tickets/lucknow-to-agra
11,Sitapur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/sitapur-to-d...
12,Delhi to Badaun,https://www.redbus.in/bus-tickets/delhi-to-badaun
13,Delhi to Sitapur (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-sit...
14,Agra to Delhi,https://www.redbus.in/bus-tickets/agra-to-delhi
15,Delhi to Moradabad,https://www.redbus.in/bus-tickets/delhi-to-mor...
16,Delhi to Lucknow,https://www.redbus.in/bus-tickets/delhi-to-luc...
17,Agra to Lucknow,https://www.redbus.in/bus-tickets/agra-to-lucknow
18,Lucknow to Varanasi,https://www.redbus.in/bus-tickets/lucknow-to-v...
19,Agra to Bareilly,https://www.redbus.in/bus-tickets/agra-to-bare...
20,Lucknow to Bareilly,https://www.redbus.in/bus-tickets/lucknow-to-b...
21,Bareilly to Agra,https://www.redbus.in/bus-tickets/bareilly-to-...
22,Delhi to Agra,https://www.redbus.in/bus-tickets/delhi-to-agra
23,Varanasi to Lucknow,https://www.redbus.in/bus-tickets/varanasi-to-...
24,Moradabad to Delhi,https://www.redbus.in/bus-tickets/moradabad-to...
25,Kanpur (Uttar Pradesh) to Jhansi,https://www.redbus.in/bus-tickets/kanpur-to-jh...
26,Delhi to Shahjahanpur (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-sha...
27,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...
28,Gorakhpur (uttar pradesh) to Lucknow,https://www.redbus.in/bus-tickets/gorakhpur-to...
29,Kanpur (Uttar Pradesh) to Bareilly,https://www.redbus.in/bus-tickets/kanpur-to-ba...
30,Lucknow to Aligarh (uttar pradesh),https://www.redbus.in/bus-tickets/lucknow-to-a...
31,Lucknow to Kanpur (Uttar Pradesh),https://www.redbus.in/bus-tickets/lucknow-to-k...
32,Delhi to Pilibhit,https://www.redbus.in/bus-tickets/delhi-to-pil...
33,Lucknow to Ballia,https://www.redbus.in/bus-tickets/lucknow-to-b...
34,Delhi to Etah (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-eta...
35,Lucknow to Gorakhpur (uttar pradesh),https://www.redbus.in/bus-tickets/lucknow-to-g...
36,Aligarh (uttar pradesh) to Lucknow,https://www.redbus.in/bus-tickets/aligarh-to-l...
37,Aligarh (uttar pradesh) to Agra,https://www.redbus.in/bus-tickets/aligarh-to-agra
38,Bareilly to Dehradun,https://www.redbus.in/bus-tickets/bareilly-to-...
39,Pilibhit to Delhi,https://www.redbus.in/bus-tickets/pilibhit-to-...
40,Bareilly to Lucknow,https://www.redbus.in/bus-tickets/bareilly-to-...
41,Delhi to Dehradun,https://www.redbus.in/bus-tickets/delhi-to-deh...
42,Varanasi to Allahabad,https://www.redbus.in/bus-tickets/varanasi-to-...
43,Lucknow to Mathura,https://www.redbus.in/bus-tickets/lucknow-to-m...
44,Jhansi to Kanpur (Uttar Pradesh),https://www.redbus.in/bus-tickets/jhansi-to-ka...
45,Dehradun to Bareilly,https://www.redbus.in/bus-tickets/dehradun-to-...
46,Kanpur (Uttar Pradesh) to Lucknow,https://www.redbus.in/bus-tickets/kanpur-to-lu...
47,Aligarh (uttar pradesh) to Greater noida (utta...,https://www.redbus.in/bus-tickets/aligarh-to-g...
48,Etah (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/etah-up-to-d...

In [138]:
df = df_UP

In [139]:
#retrive the bus details
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names = []
Route_links = []

for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(2)  

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    scrolling = True
    while scrolling:
        old_page_source = driver_k.page_source
        
        # Use ActionChains to perform a PAGE_DOWN
        ActionChains(driver_k).send_keys(Keys.PAGE_DOWN).perform()
        
        time.sleep(5)  
        
        new_page_source = driver_k.page_source
        
        if new_page_source == old_page_source:
            scrolling = False

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links.append(link)
        Route_names.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [140]:
data = {
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'End_time': End_Time_k,
    'Total_duration': Total_Duration_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k,
    "Ratings":Ratings_k,
    'Route_link': Route_links,
    'Route_name': Route_names
}

df7 = pd.DataFrame(data)

In [184]:
df7.to_csv("C:/Users/USER/Downloads/UTTRAPRADESH_redbus.csv")

In [142]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

In [143]:
driver=webdriver.Chrome()

#load the webpage

driver.get("https://www.redbus.in/online-booking/wbtc-ctc/?utm_source=rtchometile")

time.sleep(3)

driver.maximize_window()

In [144]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time

#implicit wait
wait = WebDriverWait(driver, 20)

def Westbengal_link_route(path):   
    LINKS_WESTBENGAL = []
    ROUTE_WESTBENGAL = []

    # Retrieve the route links and route names
    for i in range(1, 6):  # Adjust the range based on the actual number of pages, e.g., 4
        paths = driver.find_elements(By.XPATH, path)
        
        # Retrieve links
        for links in paths:
            d = links.get_attribute("href")
            LINKS_WESTBENGAL.append(d)
        
        # Retrieve names of the routes
        for route in paths:
            ROUTE_WESTBENGAL.append(route.text)

        try:
            # Wait for the pagination element to be present
            pagination = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@class="DC_117_paginationTable"]')))
            
            # Check if next button for the next page exists
            next_button_xpath = f'//div[@class="DC_117_pageTabs " and text()={i+1}]'
            if len(driver.find_elements(By.XPATH, next_button_xpath)) > 0:
                next_button = driver.find_element(By.XPATH, next_button_xpath)
                
                # Scroll into view and click the next button using JavaScript
                driver.execute_script("arguments[0].scrollIntoView(true);", next_button)
                time.sleep(2)  # Ensure some time for scrolling

                # Explicitly wait for the next button to be clickable
                wait.until(EC.element_to_be_clickable(next_button))
                driver.execute_script("arguments[0].click();", next_button)  # Click using JavaScript

            else:
                print(f"No more pages to paginate at step {i}")
                break  # No more pages, exit the loop

        except (NoSuchElementException, ElementClickInterceptedException) as e:
            print(f"Encountered an issue at step {i}: {e}")
            break
        
    return LINKS_WESTBENGAL, ROUTE_WESTBENGAL

# Calling the function to get links and routes
LINKS_WESTBENGAL, ROUTE_WESTBENGAL = Westbengal_link_route("//a[@class='route']")

No more pages to paginate at step 4

In [145]:
df_WB=pd.DataFrame({"Route_name":ROUTE_WESTBENGAL,"Route_link":LINKS_WESTBENGAL})
df_WB

,Route_name,Route_link
0,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...
1,Durgapur to Calcutta,https://www.redbus.in/bus-tickets/durgapur-to-...
2,Digha to Calcutta,https://www.redbus.in/bus-tickets/digha-to-kol...
3,Kolkata to Digha,https://www.redbus.in/bus-tickets/kolkata-to-d...
4,Barasat (West Bengal) to Digha,https://www.redbus.in/bus-tickets/barasat-west...
5,Kolkata to Suri,https://www.redbus.in/bus-tickets/kolkata-to-suri
6,Barasat (West Bengal) to Midnapore,https://www.redbus.in/bus-tickets/barasat-west...
7,Midnapore to Kolkata,https://www.redbus.in/bus-tickets/midnapore-to...
8,Barasat (West Bengal) to Kolaghat,https://www.redbus.in/bus-tickets/barasat-west...
9,Barasat (West Bengal) to Contai (Kanthi),https://www.redbus.in/bus-tickets/barasat-west...
10,Habra to Digha,https://www.redbus.in/bus-tickets/habra-to-digha
11,Barasat (West Bengal) to Nandakumar (west bengal),https://www.redbus.in/bus-tickets/barasat-west...
12,Kolkata to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-d...
13,Digha to Habra,https://www.redbus.in/bus-tickets/digha-to-habra
14,Midnapore to Barasat (West Bengal),https://www.redbus.in/bus-tickets/midnapore-to...
15,Kolkata to Bolpur (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-b...
16,Barasat (West Bengal) to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/barasat-west...
17,Barasat (West Bengal) to Heria,https://www.redbus.in/bus-tickets/barasat-west...
18,Haldia to Barasat (West Bengal),https://www.redbus.in/bus-tickets/haldia-to-ba...
19,Barasat (West Bengal) to Haldia,https://www.redbus.in/bus-tickets/barasat-west...
20,Haldia to Kolkata,https://www.redbus.in/bus-tickets/haldia-to-ko...
21,Barasat (West Bengal) to Debra,https://www.redbus.in/bus-tickets/barasat-west...
22,Barasat (West Bengal) to Burdwan,https://www.redbus.in/bus-tickets/barasat-west...
23,Kolkata to Bakkhali,https://www.redbus.in/bus-tickets/kolkata-to-b...
24,Kolkata to Purulia,https://www.redbus.in/bus-tickets/kolkata-to-p...
25,Durgapur (West Bengal) to Purulia,https://www.redbus.in/bus-tickets/durgapur-to-...
26,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...
27,Kolkata to Asansol (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-a...
28,Durgapur (West Bengal) to Barasat (West Bengal),https://www.redbus.in/bus-tickets/durgapur-to-...
29,Barasat (West Bengal) to Asansol (West Bengal),https://www.redbus.in/bus-tickets/barasat-west...
30,Jayrambati (West Bengal) to Barasat (West Bengal),https://www.redbus.in/bus-tickets/jayrambati-w...
31,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...
32,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...
33,Habra to Nandakumar (west bengal),https://www.redbus.in/bus-tickets/habra-to-nan...
34,Habra to Kolaghat,https://www.redbus.in/bus-tickets/habra-to-kol...
35,Kolkata to Mayapur ISKCON,https://www.redbus.in/bus-tickets/kolkata-to-m...
36,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria
37,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...

In [146]:
df = df_WB

In [147]:
#retrive the bus details
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names = []
Route_links = []

for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(2)  

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    scrolling = True
    while scrolling:
        old_page_source = driver_k.page_source
        
        # Use ActionChains to perform a PAGE_DOWN
        ActionChains(driver_k).send_keys(Keys.PAGE_DOWN).perform()
        
        time.sleep(5)  
        
        new_page_source = driver_k.page_source
        
        if new_page_source == old_page_source:
            scrolling = False

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links.append(link)
        Route_names.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [148]:
data = {
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'End_time': End_Time_k,
    'Total_duration': Total_Duration_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k,
    "Ratings":Ratings_k,
    'Route_link': Route_links,
    'Route_name': Route_names
}

df8 = pd.DataFrame(data)

In [185]:
df8.to_csv("C:/Users/USER/Downloads/WESTBENGAL_redbus.csv")